apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-app
  labels:
    app: producer-app
spec:
  selector:
    matchLabels:
      app: producer-app
  template:
    metadata:
      labels:
        app: producer-app
    spec:
      hostNetwork: true
      containers:
        - name: producer-app
          image: producer-app-image
          env:
            - name: ENV
              value: dev
            - name: JAVA_OPTS
              value: >-
                -Duser.timezone=America/Sao_Paulo -Dfile.encoding=UTF8 -Xms512m
                -Xmx1024m
